{% set name = "diffeqpy" %}
{% set version = "2.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/diffeqpy-{{ version }}.tar.gz
  sha256: 543874615c74d4737c17e0fd3779626cb22d84a85fae95d780acbf9af05534c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyjuliacall >=0.9.14
    - jill
    # jill 0.11.5 has requirement fire<0.6.0,>=0.5.0, but you have fire 0.6.0.
    - fire <0.6.0,>=0.5.0

test:
  imports:
    - diffeqpy
  requires:
    - python {{ python_min }}

about:
  home: http://github.com/SciML/diffeqpy
  summary: Solving Differential Equations in Python
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
