{% set name = "diffeqpy" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diffeqpy-{{ version }}.tar.gz
  sha256: a9ea70bbcfa56a5291c6069d678967b06547f30830f93de63e20ce31a165407c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - juliacall >=0.9.14
    - python >=3.6
    - pyjuliacall >=0.9.14
    - jill
    # jill 0.11.5 has requirement fire<0.6.0,>=0.5.0, but you have fire 0.6.0.
    - fire <0.6.0,>=0.5.0

test:
  imports:
    - diffeqpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/SciML/diffeqpy
  summary: Solving Differential Equations in Python
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
